import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> insertTestData() async {
  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testaaaaa@gmail.com",
      'name': "testaaaaaさん",
      'age': "44",
      'ageNumber': 44,
      'level': "2",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "2",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testbbbb@gmail.com",
      'name': "testbbbbさん",
      'age': "50",
      'ageNumber': 50,
      'level': "4",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );
  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testcccc@gmail.com",
      'name': "testccccさん",
      'age': "29",
      'ageNumber': 29,
      'level': "3",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testdddd@gmail.com",
      'name': "testddddさん",
      'age': "30",
      'ageNumber': 30,
      'level': "3",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testeeee@gmail.com",
      'name': "testeeeeさん",
      'age': "60",
      'ageNumber': 60,
      'level': "3",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testffff@gmail.com",
      'name': "testffffさん",
      'age': "37",
      'ageNumber': 37,
      'level': "2",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testfgggg@gmail.com",
      'name': "testggggさん",
      'age': "37",
      'ageNumber': 37,
      'level': "2",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testhhhf@gmail.com",
      'name': "teshhhさん",
      'age': "37",
      'ageNumber': 37,
      'level': "2",
      'occupation': 'staff',
      'nativeLang': "CHN",
      'country': "JPN",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testiii@gmail.com",
      'name': "tesiiiiiさん",
      'age': "37",
      'ageNumber': 37,
      'level': "2",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testaaaaa@gmail.com",
      'name': "testaaaaaさん",
      'age': "44",
      'ageNumber': 44,
      'level': "2",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "2",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testbbbb@gmail.com",
      'name': "testbbbbさん",
      'age': "50",
      'ageNumber': 50,
      'level': "4",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );
  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testcccc@gmail.com",
      'name': "testccccさん",
      'age': "29",
      'ageNumber': 29,
      'level': "3",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testdddd@gmail.com",
      'name': "testddddさん",
      'age': "30",
      'ageNumber': 30,
      'level': "3",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testeeee@gmail.com",
      'name': "testeeeeさん",
      'age': "60",
      'ageNumber': 60,
      'level': "3",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testffff@gmail.com",
      'name': "testffffさん",
      'age': "37",
      'ageNumber': 37,
      'level': "2",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testfgggg@gmail.com",
      'name': "testggggさん",
      'age': "37",
      'ageNumber': 37,
      'level': "2",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testhhhf@gmail.com",
      'name': "teshhhさん",
      'age': "37",
      'ageNumber': 37,
      'level': "2",
      'occupation': 'staff',
      'nativeLang': "CHN",
      'country': "JPN",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );

  FirebaseFirestore.instance.collection('users').add(
    {
      'email': "testiii@gmail.com",
      'name': "tesiiiiiさん",
      'age': "37",
      'ageNumber': 37,
      'level': "2",
      'occupation': 'staff',
      'nativeLang': "ENG",
      'country': "USA",
      'town': "Tokyo",
      'homeCountry': "JPN",
      'homeTown': "Toyota",
      'gender': "3",
      'placeWannaGo': 'antarctic',
      'greeting': 'おはようございます！',
      'description': 'わたしは～～～',
      'searchConditionAge': '18,30',
      'searchConditionLevel': '1,2,3,4',
      'searchConditionNativeLang': 'JPN',
      'searchConditionCountry': 'JPN,USA',
      'searchConditionGender': '1,2,3',
      'profilePhotoPath': '',
      'profilePhotoUpdateCnt': '0',
    },
  );
}
